from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import List, Optional
import uvicorn
import os
from dotenv import load_dotenv
from langchain_core.messages import HumanMessage
from langchain_agent5 import AIAgent
import uuid
import logging

## FRONTEND
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse, FileResponse

# Langchain context tracer and Langsmith SDK client
from langchain_core.tracers.context import collect_runs
from langsmith import Client

# Logging for monitoring the server
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger("Telemetry-Server")


load_dotenv()

app = FastAPI(
    title="NL2SQL Standalone Debugger",
    description="Isolated ReAct Agent runtime featuring custom AST validation and programmatic LangSmith trace tracking.",
    version="2.0.0"
)


app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # For production, replace "*" with your specific Render static frontend URL
    allow_credentials=True,
    allow_methods=["*"],  # This explicitly allows POST, OPTIONS, GET, etc.
    allow_headers=["*"],
)

# Initlialize the Langsmith SDK client
try:
    ls_client = Client()
    logger.info("LangSmith SDK client succesfully initialized.")
except Exception as e:
    ls_client = None
    logger.warning(f"LangSmith credentials unpopulated or invalid. SDK operations will use fallback telemetry: {str(e)}") 

# 1. Mount the folder containing telemetry.html
app.mount("/static", StaticFiles(directory="static"), name="static")

# 2. Add an explicit route to serve the telemetry dashboard
@app.get("/telemetry")
async def serve_telemetry():
    return FileResponse("static/telemetry.html")

# Request Schema for the standalone execution target
class AgentExecutionRequest(BaseModel):
    message: str = Field(..., description="Natural language question or database mutation command.")
    working_dir: str = Field(".", description="The relative excecution directory or file-system operations.")
    
# Cached Agent instance helper
_agent_instance = None    
    
def get_standalone_agent(working_dir: str = "."):
    global _agent_instance
    resolved_path = os.path.abspath(working_dir)
    if _agent_instance is None or _agent_instance.working_dir != resolved_path:
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            raise ValueError("GROQ_API_KEY environment variable is unpopulated.")
        logger.info(f"Instantiating AIAgent instance at: {resolved_path}") 
        _agent_instance = AIAgent(api_key=api_key, working_dir=resolved_path)
    return _agent_instance

@app.post("/agent")
async def execute_agent(req: AgentExecutionRequest):
    """Executes the ReAct agent within a run-collection block,
    capturing the exact LangSmith execution ID to route telemetry down the line
    """
    
    try:
        agent = get_standalone_agent(req.working_dir)
        
        # Collect tracing runs dynamically from the active execution thread
        with collect_runs() as run_collector:
            result = agent.chat(req.message)
            
            # Extract the unique execution ID generated by LangChain
            run_id = None
            if run_collector.traced_runs:
                run_id = str(run_collector.traced_runs[0].id)
                logger.info(f"Dispatched LangChain execution trace recorded with ID: {run_id}")
        
        # Format polymorphic outputs
        if isinstance(result, dict) and result.get("type") == "db_result":
            res = result.get("result")
            return {
                "type": "db_result",
                "run_id": run_id,
                "sql": getattr(res, "sql", "Unknown SQL Query"),
                "row_count": getattr(res, "row_count", 0),
                "error": getattr(res, "error", None),
                "columns": getattr(res, "columns", []),
                "rows_preview": getattr(res, "rows", [])[:10] if hasattr(res, "rows") else [],
                "file_path": getattr(res, "file_path", None)
            }
        else:
            # Catch plain string fallbacks or text responses
            content = result.get("content", str(result)) if isinstance(result, dict) else str(result)
            return {
                "type": "text",
                "run_id": run_id,
                "content": result.get("content", str(result))
            }
            
    except Exception as e:
        logger.error(f"Execution Error within agent loop: {str(e)}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))
    
    
    
@app.get("/agent/trace/{run_id}")
async def get_agent_trace(run_id: str):
    """
    Interrogates the LangSmith platform API programmatically using the SDK client.
    Reconstructs the hierarchical child steps (individual tool executions, LLM calls) as a clean array.
    """
    if not ls_client:
        raise HTTPException(
            status_code=503, 
            detail="Telemetry Service Unavailable: LangSmith Client credentials are unconfigured."
        )
    
    try:
        # Retrieve the master run trace from LangSmith
        run = ls_client.read_run(run_id)
        
        # Retrieve all child nodes corresponding to the parent run_id
        child_runs = list(ls_client.list_runs(trace_id=run_id))
        
        steps = []
        for child in sorted(child_runs, key=lambda x: x.start_time):
            # Skip the root run itself so we don't duplicate it in the UI steps
            if str(child.id) == run_id:
                continue
            # Formulate individual trace nodes
            steps.append({
                "name": child.name,
                "type": child.run_type or "unknown",
                "status": "error" if child.error else "success",
                "latency_ms": (child.end_time - child.start_time).total_seconds() * 1000 if child.end_time else 0,
                "inputs": child.inputs or {},
                "outputs": child.outputs or {},
                "error": child.error
            })
            
        return {
            "run_id": run_id,
            "name": run.name,
            "status": "error" if run.error else "success",
            "latency_ms": (run.end_time - run.start_time).total_seconds() * 1000 if run.end_time else 0,
            "error": run.error,
            "steps": steps
        }
        
    except Exception as e:
        logger.error(f"Programmatic trace fetch failed for run {run_id}: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to interrogate telemetry log: {str(e)}")

# Mount static and UI files
os.makedirs("static", exist_ok=True)
app.mount("/static", StaticFiles(directory="static"), name="static")

@app.get("/")
async def get_root_interface():
    """Serves the unified, programmatic tracing console directly."""
    return FileResponse("static/telemetry.html")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app_standalone:app", host="0.0.0.0", port=8000, reload=True)
        
    
    
    
    
    

    

    
    
